"use client";

import Image, {ImageProps} from "next/image";
import {useState} from "react";
import {cn} from "@/lib/utils";

interface BlurImageProps extends Omit<ImageProps, "placeholder" | "blurDataURL"> {
  /**
   * Blur placeholder data URL generated by Plaiceholder
   */
  blurDataURL?: string;
  /**
   * CSS class to apply when the image is loading
   */
  loadingClassName?: string;
}

/**
 * Enhanced Image component with blur placeholder and loading state
 */
export function BlurImage({src, alt, className, blurDataURL, loadingClassName, ...props}: BlurImageProps) {
  const [isLoading, setIsLoading] = useState(true);

  return (
    <Image
      src={src}
      alt={alt}
      className={cn(className, isLoading && loadingClassName)}
      placeholder={blurDataURL ? "blur" : "empty"}
      blurDataURL={blurDataURL}
      onLoad={() => setIsLoading(false)}
      {...props}
    />
  );
}
